# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HouseOfToday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HouseOfToday
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'GoogleSignIn'
  pod 'naveridlogin-sdk-ios'

end
